const mock_rides = [
  {
    ride_id: "5",
    driver_id: "16",
    origin_address: "Kubwa, Abuja",
    destination_address: "Central Area, Abuja",
    origin_latitude: "9.1861",
    origin_longitude: "7.3748",
    destination_latitude: "9.0574",
    destination_longitude: "7.4958",
    ride_time: 340,
    fare_price: "4000",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-06 15:22:59.9832",
    category: "Mobility",
    subcategory: "Rides",
    type: "Economy",
    driver: {
      id: "16",
      first_name: "Ibrahim",
      last_name: "Lawal",
      phone_number: "08056789012",
      profile_picture: "https://example.com/profile5.jpg",
      car_image: "https://example.com/car5.jpg",
      car_model: "Kia Rio",
      car_color: "White",
      car_plate_number: "BWR5432T",
      car_seats: "4",
      rating: "4.3",
    },
  },
  {
    ride_id: "6",
    driver_id: "17",
    origin_address: "Garki, Abuja",
    destination_address: "Jabi, Abuja",
    origin_latitude: "9.0261",
    origin_longitude: "7.4853",
    destination_latitude: "9.0706",
    destination_longitude: "7.4373",
    ride_time: 210,
    fare_price: "2800",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-06 18:45:10.0000",
    category: "Mobility",
    subcategory: "Rides",
    type: "Luxury",
    driver: {
      id: "17",
      first_name: "Chidinma",
      last_name: "Nwosu",
      phone_number: "08067890123",
      profile_picture: "https://example.com/profile6.jpg",
      car_image: "https://example.com/car6.jpg",
      car_model: "Peugeot 406",
      car_color: "Red",
      car_plate_number: "ABC7654D",
      car_seats: "4",
      rating: "4.9",
    },
  },
  {
    ride_id: "7",
    driver_id: "18",
    origin_address: "Wuse 2, Abuja",
    destination_address: "Utako, Abuja",
    origin_latitude: "9.081999",
    origin_longitude: "7.4891",
    destination_latitude: "9.0726",
    destination_longitude: "7.4546",
    ride_time: 180,
    fare_price: "1500",
    payment_status: "Paid",
    user_id: "2",
    created_at: "2025-10-07 09:12:45.0000",
    category: "Mobility",
    subcategory: "Rides",
    type: "Shared Rides",
    driver: {
      id: "18",
      first_name: "Uche",
      last_name: "Okoro",
      phone_number: "08034567890",
      profile_picture: "https://example.com/profile7.jpg",
      car_image: "https://example.com/car7.jpg",
      car_model: "Toyota Sienna",
      car_color: "Blue",
      car_plate_number: "XYZ123FG",
      car_seats: "6",
      rating: "4.6",
    },
  },
  {
    ride_id: "8",
    driver_id: "19",
    origin_address: "Asokoro, Abuja",
    destination_address: "Maitama, Abuja",
    origin_latitude: "9.0523",
    origin_longitude: "7.5127",
    destination_latitude: "9.0765",
    destination_longitude: "7.4978",
    ride_time: 250,
    fare_price: "3500",
    payment_status: "Paid",
    user_id: "3",
    created_at: "2025-10-07 13:30:22.0000",
    category: "Mobility",
    subcategory: "Shuttle Buses",
    type: "Standard",
    driver: {
      id: "19",
      first_name: "Amina",
      last_name: "Abdullahi",
      phone_number: "08011223344",
      profile_picture: "https://example.com/profile8.jpg",
      car_image: "https://example.com/bus1.jpg",
      car_model: "Toyota Hiace",
      car_color: "White",
      car_plate_number: "FCT404AA",
      car_seats: "15",
      rating: "4.7",
    },
  },
  {
    ride_id: "9",
    driver_id: "20",
    origin_address: "Area 10, Abuja",
    destination_address: "Kuje, Abuja",
    origin_latitude: "8.9849",
    origin_longitude: "7.4134",
    destination_latitude: "8.8892",
    destination_longitude: "7.2279",
    ride_time: 500,
    fare_price: "8000",
    payment_status: "Paid",
    user_id: "4",
    created_at: "2025-10-07 16:50:00.0000",
    category: "Logistics",
    subcategory: "Haulage",
    type: "Mini Truck",
    driver: {
      id: "20",
      first_name: "David",
      last_name: "Oladipo",
      phone_number: "08099887766",
      profile_picture: "https://example.com/profile9.jpg",
      car_image: "https://example.com/truck1.jpg",
      car_model: "Hyundai HD65",
      car_color: "Green",
      car_plate_number: "KUJ334FF",
      car_seats: "2",
      rating: "4.4",
    },
  },
  {
    ride_id: "10",
    driver_id: "21",
    origin_address: "Nyanya, Abuja",
    destination_address: "Lugbe, Abuja",
    origin_latitude: "9.0076",
    origin_longitude: "7.5401",
    destination_latitude: "8.9968",
    destination_longitude: "7.4468",
    ride_time: 300,
    fare_price: "2000",
    payment_status: "Paid",
    user_id: "5",
    created_at: "2025-10-08 08:20:10.0000",
    category: "Logistics",
    subcategory: "Dispatch Bikes",
    type: "Standard",
    driver: {
      id: "21",
      first_name: "Blessing",
      last_name: "Effiong",
      phone_number: "08077889900",
      profile_picture: "https://example.com/profile10.jpg",
      car_image: "https://example.com/bike1.jpg",
      car_model: "Honda Ace",
      car_color: "Black",
      car_plate_number: "NJA101JJ",
      car_seats: "1",
      rating: "4.8",
    },
  },
  {
    ride_id: "11",
    driver_id: "22",
    origin_address: "Airport Road, Abuja",
    destination_address: "Gwarinpa, Abuja",
    origin_latitude: "9.0064",
    origin_longitude: "7.2634",
    destination_latitude: "9.0892",
    destination_longitude: "7.3912",
    ride_time: 420,
    fare_price: "6000",
    payment_status: "Paid",
    user_id: "6",
    created_at: "2025-10-08 11:44:20.0000",
    category: "Emergency",
    subcategory: "Ambulance",
    type: "Standard",
    driver: {
      id: "22",
      first_name: "Rahim",
      last_name: "Yusuf",
      phone_number: "08033445566",
      profile_picture: "https://example.com/profile11.jpg",
      car_image: "https://example.com/ambulance1.jpg",
      car_model: "Ford Transit",
      car_color: "White",
      car_plate_number: "EMG101AA",
      car_seats: "4",
      rating: "4.5",
    },
  },
  {
    ride_id: "12",
    driver_id: "23",
    origin_address: "Zuba, Abuja",
    destination_address: "Gwagwalada, Abuja",
    origin_latitude: "9.1143",
    origin_longitude: "7.2405",
    destination_latitude: "8.9417",
    destination_longitude: "7.0856",
    ride_time: 620,
    fare_price: "9500",
    payment_status: "Paid",
    user_id: "7",
    created_at: "2025-10-08 14:33:00.0000",
    category: "Emergency",
    subcategory: "Towing Vehicles",
    type: "Flatbed",
    driver: {
      id: "23",
      first_name: "Femi",
      last_name: "Adeyemi",
      phone_number: "08066554433",
      profile_picture: "https://example.com/profile12.jpg",
      car_image: "https://example.com/towing1.jpg",
      car_model: "Isuzu Flatbed",
      car_color: "Yellow",
      car_plate_number: "TOY909BB",
      car_seats: "2",
      rating: "4.2",
    },
  },
];

export default mock_rides;
