const mock_driver = [
  {
    driver_id: "16",
    first_name: "Ibrahim",
    last_name: "Lawal",
    phone_number: "08056789012",
    profile_picture: "https://example.com/profile5.jpg",
    car_image: "https://example.com/car5.jpg",
    car_model: "Kia Rio",
    car_color: "White",
    car_plate_number: "BWR5432T",
    car_seats: "4",
    rating: "4.3",
    category: "Mobility",
    subcategory: "Rides",
    type: "Economy",
  },
  {
    driver_id: "17",
    first_name: "Chidinma",
    last_name: "Nwosu",
    phone_number: "08067890123",
    profile_picture: "https://example.com/profile6.jpg",
    car_image: "https://example.com/car6.jpg",
    car_model: "Peugeot 406",
    car_color: "Red",
    car_plate_number: "ABC7654D",
    car_seats: "4",
    rating: "4.9",
    category: "Mobility",
    subcategory: "Rides",
    type: "Luxury",
  },
  {
    driver_id: "18",
    first_name: "Uche",
    last_name: "Okoro",
    phone_number: "08034567890",
    profile_picture: "https://example.com/profile7.jpg",
    car_image: "https://example.com/car7.jpg",
    car_model: "Toyota Sienna",
    car_color: "Blue",
    car_plate_number: "XYZ123FG",
    car_seats: "6",
    rating: "4.6",
    category: "Mobility",
    subcategory: "Rides",
    type: "Shared Rides",
  },
  {
    driver_id: "19",
    first_name: "Amina",
    last_name: "Abdullahi",
    phone_number: "08011223344",
    profile_picture: "https://example.com/profile8.jpg",
    car_image: "https://example.com/bus1.jpg",
    car_model: "Toyota Hiace",
    car_color: "White",
    car_plate_number: "FCT404AA",
    car_seats: "15",
    rating: "4.7",
    category: "Mobility",
    subcategory: "Shuttle Buses",
    type: "Standard",
  },
  {
    driver_id: "20",
    first_name: "David",
    last_name: "Oladipo",
    phone_number: "08099887766",
    profile_picture: "https://example.com/profile9.jpg",
    car_image: "https://example.com/truck1.jpg",
    car_model: "Hyundai HD65",
    car_color: "Green",
    car_plate_number: "KUJ334FF",
    car_seats: "2",
    rating: "4.4",
    category: "Logistics",
    subcategory: "Haulage",
    type: "Mini Truck",
  },
  {
    driver_id: "21",
    first_name: "Blessing",
    last_name: "Effiong",
    phone_number: "08077889900",
    profile_picture: "https://example.com/profile10.jpg",
    car_image: "https://example.com/bike1.jpg",
    car_model: "Honda Ace",
    car_color: "Black",
    car_plate_number: "NJA101JJ",
    car_seats: "1",
    rating: "4.8",
    category: "Logistics",
    subcategory: "Dispatch Bikes",
    type: "Standard",
  },

  {
    driver_id: "22",
    first_name: "Rahim",
    last_name: "Yusuf",
    phone_number: "08033445566",
    profile_picture: "https://example.com/profile11.jpg",
    car_image: "https://example.com/ambulance1.jpg",
    car_model: "Ford Transit",
    car_color: "White",
    car_plate_number: "EMG101AA",
    car_seats: "4",
    rating: "4.5",
    category: "Emergency",
    subcategory: "Ambulance",
    type: "Standard",
  },
];

export default mock_driver;
