const mock_rides = [
  {
    ride_id: "1",
    driver_id: "2",
    origin_address: "Apo, Abuja",
    destination_address: "Gwarinpa, Abuja",
    origin_latitude: "9.0095",
    origin_longitude: "7.4898",
    destination_latitude: "9.1012",
    destination_longitude: "7.4152",
    ride_time: 291,
    fare_price: "2500",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-01 05:19:20.4355",
    driver: {
      id: "2",
      first_name: "Kelvin",
      last_name: "Okon",
      phone_number: "08012345678",
      profile_picture: "https://example.com/profile1.jpg",
      car_image: "https://example.com/car1.jpg",
      car_model: "Toyota Camry",
      car_color: "Black",
      car_plate_number: "ABC1234",
      car_seats: "4",
      rating: "4.5",
    },
  },
  {
    ride_id: "2",
    driver_id: "4",
    origin_address: "Lugbe, Abuja",
    destination_address: "Gudu, Abuja",
    origin_latitude: "8.9935",
    origin_longitude: "7.4065",
    destination_latitude: "9.0264",
    destination_longitude: "7.4826",
    ride_time: 302,
    fare_price: "3500",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-03 11:12:44.1221",
    driver: {
      id: "4",
      first_name: "Adamu",
      last_name: "Mohammed",
      phone_number: "08023456789",
      profile_picture: "https://example.com/profile2.jpg",
      car_image: "https://example.com/car2.jpg",
      car_model: "Honda Accord",
      car_color: "Silver",
      car_plate_number: "XYZ9876",
      car_seats: "4",
      rating: "4.7",
    },
  },
  {
    ride_id: "3",
    driver_id: "12",
    origin_address: "Lokogoma, Abuja",
    destination_address: "Asokoro, Abuja",
    origin_latitude: "8.9981",
    origin_longitude: "7.4746",
    destination_latitude: "9.0437",
    destination_longitude: "7.5112",
    ride_time: 250,
    fare_price: "3000",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-04 09:33:10.7723",
    driver: {
      id: "12",
      first_name: "Uche",
      last_name: "Okeke",
      phone_number: "08034567890",
      profile_picture: "https://example.com/profile3.jpg",
      car_image: "https://example.com/car3.jpg",
      car_model: "Toyota Avensis",
      car_color: "Gray",
      car_plate_number: "DEF5678",
      car_seats: "4",
      rating: "5.0",
    },
  },
  {
    ride_id: "4",
    driver_id: "15",
    origin_address: "Wuse 2, Abuja",
    destination_address: "Maitama, Abuja",
    origin_latitude: "9.0579",
    origin_longitude: "7.4888",
    destination_latitude: "9.0765",
    destination_longitude: "7.4969",
    ride_time: 180,
    fare_price: "2200",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-05 07:10:10.1234",
    driver: {
      id: "15",
      first_name: "Zainab",
      last_name: "Usman",
      phone_number: "08045678901",
      profile_picture: "https://example.com/profile4.jpg",
      car_image: "https://example.com/car4.jpg",
      car_model: "Hyundai Elantra",
      car_color: "Blue",
      car_plate_number: "KJA3345F",
      car_seats: "4",
      rating: "4.6",
    },
  },
  {
    ride_id: "5",
    driver_id: "16",
    origin_address: "Kubwa, Abuja",
    destination_address: "Central Area, Abuja",
    origin_latitude: "9.1861",
    origin_longitude: "7.3748",
    destination_latitude: "9.0574",
    destination_longitude: "7.4958",
    ride_time: 340,
    fare_price: "4000",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-06 15:22:59.9832",
    driver: {
      id: "16",
      first_name: "Ibrahim",
      last_name: "Lawal",
      phone_number: "08056789012",
      profile_picture: "https://example.com/profile5.jpg",
      car_image: "https://example.com/car5.jpg",
      car_model: "Kia Rio",
      car_color: "White",
      car_plate_number: "BWR5432T",
      car_seats: "4",
      rating: "4.3",
    },
  },
  {
    ride_id: "6",
    driver_id: "17",
    origin_address: "Garki, Abuja",
    destination_address: "Jabi, Abuja",
    origin_latitude: "9.0261",
    origin_longitude: "7.4853",
    destination_latitude: "9.0706",
    destination_longitude: "7.4373",
    ride_time: 210,
    fare_price: "2800",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-06 18:45:10.0000",
    driver: {
      id: "17",
      first_name: "Chidinma",
      last_name: "Nwosu",
      phone_number: "08067890123",
      profile_picture: "https://example.com/profile6.jpg",
      car_image: "https://example.com/car6.jpg",
      car_model: "Peugeot 406",
      car_color: "Red",
      car_plate_number: "ABC7654D",
      car_seats: "4",
      rating: "4.9",
    },
  },
  {
    ride_id: "7",
    driver_id: "18",
    origin_address: "Utako, Abuja",
    destination_address: "Mpape, Abuja",
    origin_latitude: "9.0765",
    origin_longitude: "7.4562",
    destination_latitude: "9.1002",
    destination_longitude: "7.4811",
    ride_time: 260,
    fare_price: "3300",
    payment_status: "Paid",
    user_id: "1",
    created_at: "2025-10-07 06:10:12.5432",
    driver: {
      id: "18",
      first_name: "Tunde",
      last_name: "Adewale",
      phone_number: "08078901234",
      profile_picture: "https://example.com/profile7.jpg",
      car_image: "https://example.com/car7.jpg",
      car_model: "Mazda 3",
      car_color: "Green",
      car_plate_number: "FCT0987Y",
      car_seats: "4",
      rating: "4.8",
    },
  },
];

export default mock_rides;
